CREATE TABLE [dbo].[Patient] (
    [PatientId]                BIGINT       IDENTITY (1, 1) NOT NULL,
    [LastName]                 VARCHAR (35) NOT NULL,
    [FirstName]                VARCHAR (35) NOT NULL,
    [MiddleName]               VARCHAR (35) NULL,
    [PatientStatus]            BIT          NOT NULL,
    [GenderId]                 BIGINT       NULL,
    [HomePhone]                VARCHAR (35) NULL,
    [CellPhone]                VARCHAR (35) NULL,
    [WorkPhone]                VARCHAR (35) NULL,
    [EmailAddress]             VARCHAR (35) NULL,
    [DateofBirth]              DATETIME     NULL,
    [Company]                  VARCHAR (35) NULL,
    [EmergencyContactName]     VARCHAR (35) NULL,
    [EmergencyContactPhone]    VARCHAR (35) NULL,
    [GorvernmentId]            VARCHAR (70) NULL,
    [Address1]                 VARCHAR (70) NULL,
    [Address2]                 VARCHAR (70) NULL,
    [City]                     VARCHAR (70) NULL,
    [Province]                 VARCHAR (70) NULL,
    [PostalCode]               VARCHAR (70) NULL,
    [CountryId]                BIGINT       NOT NULL,
    [PerferredMethodofContact] VARCHAR (70) NULL,
    [MaritalStatus]            VARCHAR (70) NULL,
    [DemographicId]            BIGINT       NOT NULL,
    [CreateDate]               DATETIME     CONSTRAINT [DF_PatientId_CreateDate] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]                VARCHAR (60) CONSTRAINT [DF_PatientId_CreatedBy] DEFAULT (suser_sname()) NOT NULL,
    [UpdateDate]               DATETIME     NULL,
    [UpdatedBy]                VARCHAR (60) NULL,
    CONSTRAINT [PK_Patient_Patient] PRIMARY KEY CLUSTERED ([PatientId] ASC),
    CONSTRAINT [FK_Patient_Demographic] FOREIGN KEY ([DemographicId]) REFERENCES [dbo].[Demographic] ([DemographicId]),
    CONSTRAINT [FK_Patient_Gender] FOREIGN KEY ([GenderId]) REFERENCES [dbo].[Gender] ([GenderId])
);

